## 두번째 과제입니다.

우리는 파이썬 문법 2 파트에서 컨테이너 자료, 반복문, 함수 등에 대해서 배웠습니다.

이에 대한 과제를 제공해 드립니다.

과제를 하시는 동안 정보검색은 적극 권장됩니다.

## 컨테이너 자료

# Q1

num_list 라는 변수에 1~10까지의 숫자를 입력합니다.

짝수만 있는 리스트, 홀수만 있는 리스트를 각각 새로운 변수에 할당하고 호출해보세요.

In [126]:
# write your code here!!

num_list = []

for i in range(1, 11):
    num_list.append(i)

even = []
odd = []
    
for i in num_list:
    if i % 2 == 0:
        even.append(i)
    else :
        odd.append(i)
        
print(even)
print(odd)

[2, 4, 6, 8, 10]
[1, 3, 5, 7, 9]


# Q2

주어진 두 리스트와 리스트의 연산, 추가, 삭제 등의 함수를 활용해서 다음과 같은 결과를 만들어봅시다.

```python

name1 = ["짱구", "철수", "유리", "맹구", "훈이"]
name2 = ["미선", "형만", "흰둥이", "퉁퉁이", "도라에몽"]

```

결과 : `["진구", "짱구", "철수", "맹구", "미선", "핑핑이", "흰둥이", "퉁퉁이", "도라에몽", "비실이"]`

In [21]:
# write your code here!!
name1 = ["짱구", "철수", "유리", "맹구", "훈이"]
name2 = ["미선", "형만", "흰둥이", "퉁퉁이", "도라에몽"]

name = name1 + name2

del name[2]
del name[3]
name[4] = "핑핑이"
name.insert(0, "진구")
name.append("비실이")

name

['진구', '짱구', '철수', '맹구', '미선', '핑핑이', '흰둥이', '퉁퉁이', '도라에몽', '비실이']

# Q3

아래 문제를 해결하세요.

1. 리스트의 합을 출력하세요.
2. 리스트의 평균을 출력하세요
3. 리스트에 저장된 데이터 개수를 출력하세요,

```python

num = [3, 4, 10, 2, 1]
```

In [24]:
# write your code here!!

num = [3, 4, 10, 2, 1]
sum = 0

for i in num:
    sum += i
    
print(sum)
print(sum / len(num))
print(len(num))

20
4.0
5


# Q4

아래의 리스트를 주어진 결과로 출력해주세요.

```python
characters = ["짱구", "철수", "유리", "맹구", "훈이"]
```

결과 : `짱구&철수&유리&맹구&훈이`

<a href="https://ourcstory.tistory.com/46"> 참고자료 </a>

In [30]:
# write your code here!!
characters = ["짱구", "철수", "유리", "맹구", "훈이"]

character_string = "&".join(characters)
character_string

'짱구&철수&유리&맹구&훈이'

In [38]:
# better
print("&".join(characters))
print(characters)

짱구&철수&유리&맹구&훈이
['짱구', '철수', '유리', '맹구', '훈이']


# Q5.

아래의 문자열을 주어진 결과로 출력해주세요.

```python
name = "짱구, 철수, 유리, 맹구, 훈이"
```

결과1 : `["짱구", "철수", "유리", "맹구", "훈이"]`

결과2 : `짱구&철수&유리&맹구&훈이`

In [39]:
# write your code here!!
name = "짱구, 철수, 유리, 맹구, 훈이"

#결과1
character = []
character.append(name[0:2])
character.append(name[4:6])
character.append(name[8:10])
character.append(name[12:14])
character.append(name[16:18])
print(character)

#결과2
print("&".join(characters))

['짱구', '철수', '유리', '맹구', '훈이']
짱구&철수&유리&맹구&훈이


# Q6.

다음 코드의 결과를 예측해봅니다. 그리고 그 이유를 생각해봅시다.

```python
characters = ["짱구", "철수", "유리", "맹구", "훈이"]
characters_copy = characters
characters_copy[0] = "도라에몽"
print(characters)
```

In [40]:
# write your code here!!
characters = ["짱구", "철수", "유리", "맹구", "훈이"]
characters_copy = characters
characters_copy[0] = "도라에몽"
print(characters)

['도라에몽', '철수', '유리', '맹구', '훈이']


characters_copy 리스트의 0번에 해당하는 변수가 Update 되어서 짱구에서 도라에몽으로 변경됨.

# Q7.

로그인 어플 개발하기 문제

user_id = ['red', 'blue', 'green', 'pink']

user_pwd = ['123', 'qwe', '456', '789']

유저 아이디와 비밀번호는 각각 다음과 같이 주어져 있습니다.

사용자에게 아이디와 비밀번호를 input함수로 입력 받고,

입력받은 아이디와 비밀번호가 일치하면 '안녕하세요 ~님'을 출력하고

아이디는 일치하지만, 비밀번호는 일치하지 않는다면 '비밀번호가 틀렸습니다.'를 출력하고

아이디가 일치하지 않는다면 '존재하지 않는 아이디입니다.'를 출력하는 함수를 만들어보고, 정상작동하는지 확인해봅시다.

help)

인덱스를 찾는 내장함수, 리스트.index("요소")

어떤 요소의 존재 여부를 확인하는 방법, in, not in

In [44]:
# write your code here!!
user_id = ['red', 'blue', 'green', 'pink']
user_pwd = ['123', 'qwe', '456', '789']

new_id = input("new_id = ")
new_pwd = input("new_pwd = ")

if new_id in user_id and new_pwd in user_pwd :
    print(f"안녕하세요 {new_id}님")

elif new_id in user_id and new_pwd not in user_pwd :
    print("비밀번호가 틀렸습니다.")
    
elif new_id not in user_id :
    print("존재하지 않는 아이디입니다.")

new_id = 123
new_pwd = ee
존재하지 않는 아이디입니다.


# Q8.

다음의 아이디와 비밀번호 데이터를 딕셔너리로 구성하세요.

`아이디: ['red', 'blue', 'green', 'pink']`

`비밀번호: ['123', 'qwe', '456', '789']`

In [3]:
# write your code here!!

login = {'red' : '123', 'blue' : 'qwe', 'green' : '456', 'pink' : '789'}

In [7]:
user_id = ['red', 'blue', 'green', 'pink']

user_pwd = ['123', 'qwe', '456', '789']

In [8]:
# Session 1

user_info = {}
for i in range(len(user_id)):
    user_info[user_id[i]] = user_pwd[i]

user_info

{'red': '123', 'blue': 'qwe', 'green': '456', 'pink': '789'}

In [12]:
# Session 2

print(zip(user_id, user_pwd))
dict(zip(user_id, user_pwd))

{'red': '123', 'blue': 'qwe', 'green': '456', 'pink': '789'}

# Q9.

Q8.문제에서 만든 딕셔너리에 다음의 데이터를 추가하세요.

`아이디: "black"`

`비밀번호: "sohot"`

In [5]:
# write your code here!!

login['black'] = "sohot"
login

{'red': '123', 'blue': 'qwe', 'green': '456', 'pink': '789', 'black': 'sohot'}

# Q10.

Q8, Q9에서 만든 딕셔너리를 바탕으로 아래를 푸세요.

1. blue의 비밀번호를 "blue123"으로 변경해주세요.
2. black의 정보를 삭제해주세요.

In [6]:
# write your code here!!

login['blue'] = "blue123"
del login['black']
login

{'red': '123', 'blue': 'blue123', 'green': '456', 'pink': '789'}

# Q11.

딕셔너리를 사용한 로그인 어플 개발하기 문제

user_info = {'red': '123', 'blue': 'blue123', 'green': '456', 'pink': '789'}

사용자 정보가 위와 같이 주어질때, 로그인 문제를 풀어보세요. 문제는 위의 `Q7.` 문제와 같습니다.

In [50]:
# write your code here!!
user_info = {'red': '123', 'blue': 'blue123', 'green': '456', 'pink': '789'}

new_id = input("new_id = ")
new_pwd = input("new_pwd = ")

if new_id in list(user_info.keys()) and new_pwd in list(user_info.values()) :
    print(f"안녕하세요 {new_id}님")

elif new_id in list(user_info.keys()) and new_pwd not in list(user_info.values()) :
    print("비밀번호가 틀렸습니다.")
    
elif new_id not in list(user_info.keys()) :
    print("존재하지 않는 아이디입니다.")

new_id = red1
new_pwd = qe
존재하지 않는 아이디입니다.


## 반복문(while, for)

# Q12.

1~10까지의 숫자를 입력받고, 입력 받은 숫자가 홀수인지 짝수인지 판별하는 코드를 작성해보세요.

단, 1~10까지의 숫자가 아니라면 다시 입력을 받아야합니다.

In [59]:
# write your code here!!
num = int(input("enter random number = "))

while num not in range(1,11):
    num = int(input("enter random number = "))
if num % 2 == 0:
    print("even")
else:
    print("odd")

enter random number = 11
enter random number = 11
enter random number = 11
enter random number = 11
enter random number = 14
enter random number = 10
even


# Q13.

다음과 같은 리스트가 주어졌을 때, 캐릭터의 이름과 캐릭터 글자수를 출력하세요.

```python

characters = ["사고뭉치 짱구", "시크한 철수", "화난유리", "코맹맹이 맹구", "쫄보 훈이"]

```

결과예시

`사고뭉치 짱구 7`

`시크한 철수 6`

~~

In [61]:
# write your code here!!
characters = ["사고뭉치 짱구", "시크한 철수", "화난유리", "코맹맹이 맹구", "쫄보 훈이"]

for i in characters:
    print(f"{i} {len(i)}")

사고뭉치 짱구 7
시크한 철수 6
화난유리 4
코맹맹이 맹구 7
쫄보 훈이 5


# Q14.

반복문을 사용해서, num에서 홀수만 출력하는 코드를 만드세요.

```pyhon
num = [1,2,3,4,5,6,7,8,9,10]
```

In [65]:
# write your code here!!
num = [1,2,3,4,5,6,7,8,9,10]

for i in num:
    if int(i) % 2 == 1:
        print(f"{i}")

1
3
5
7
9


# Q15.

반복문을 사용해서, Q14.의 num에서 `1, 2, 3을 제외하고` 출력해주세요.

In [66]:
# write your code here!!
num = [1,2,3,4,5,6,7,8,9,10]

for i in num[3::]:
    print(f"{i}")

4
5
6
7
8
9
10


# Q16
아래의 num 리스트를 결과와 같이 바꿔주세요.

```python
num = [12.5, 33.03, 20.78, 35.12]```

결과: `[12, 33, 20, 35]`

In [69]:
# write your code here!!
import math

num = [12.5, 33.03, 20.78, 35.12]

n = 0
for i in num:
    num[n] = math.floor(i)
    n += 1
    
num

[12, 33, 20, 35]

# Q17.

김철수씨는 회사에서 문서분류 직무를 맡고 있다. 김계란씨는 일일이 문서 확장자를 확인하며 같은 확장자끼리 분류했다. 문서분류량이 엄청난 날에는 야근하기가 일쑤였다.

이대로는 안돼겠다고 생각한 김철수씨는 최근에 프로그래밍을 배우기 시작했다.

프로그래밍을 배우고 난 뒤로부터는 매일 칼퇴근을 하고 취미생활까지 할 여유가 생겼다고 한다.

김철수씨가 평소 하는 일은 다음과 같다.

1. 김철수씨의 회사엔 `txt, py, java`  이렇게 3가지의 파일이 존재한다.
2. 김철수씨는 확장자가 같은 파일을 동일한 리스트에 보관한다.

```python
messy_files = ["wow.py", "test.txt", "haha.java", "really_final.py", "real_really_final.java", "test2.py", "whatthef.txt"]
```

햇살 좋은 어느날, 김철수씨는 직장 상사 유상사씨로부터 `messy_files`를 분류해달라는 부탁을 받았다. 김철수씨는 피식 웃으며 자신감있게 도와주겠다고 말했다.

문제 : 김철수씨의 체면이 구겨지지 않도록 `txt, py, java` 각각 확장자에 따라 text, python, java라는 변수명을 가진 리스트에 분류하는 코드를 작성해주세요.

In [14]:
# QnA : Split 함수는 특정 문자열을 기준으로 전체 문자열을 나눠주는 역할, 확장자부분만 끌어오기

# write your code here!!
messy_files = ["wow.py", "test.txt", "haha.java", "really_final.py", "real_really_final.java", "test2.py", "whatthef.txt"]

# 'py' in messy_files[0].split(".", 2)

py = []
txt = []
java = []

for i in messy_files:
    if 'py' in i.split(".", 2):
        py.append(i)
    elif 'txt' in i.split(".", 2):
        txt.append(i)
    else:
        java.append(i)

print(py)
print(txt)
print(java)

['wow.py', 'really_final.py', 'test2.py']
['test.txt', 'whatthef.txt']
['haha.java', 'real_really_final.java']


In [22]:
# Session

py = []
java = []
txt = []

# find function

#start_point = messy_files[0].find(".")
#
#messy_files[0][start_point+1:]
#
#for file_name in messy_files:
#    start_point = file_name.find(".")+1
#    classification = file_name[start_point:]
#    
#    if classification == "py":
#        py.append(file_name)
#    elif classification == "txt":
#        txt.append(file_name)
#    else :
#        java.append(file_name)

# split

for file_name in messy_files:
    classification = file_name.split(".")[1]
    
    if classification == "py":
        py.append(file_name)
    elif classification == "txt":
        txt.append(file_name)
    else :
        java.append(file_name)

py, java, txt

(['wow.py', 'really_final.py', 'test2.py'],
 ['haha.java', 'real_really_final.java'],
 ['test.txt', 'whatthef.txt'])

# Q18.

for문의 중첩을 활용해서

`1, 2, 3, 4`

`5, 6, 7, 8`

`9, 10, 11, 12`

`13, 14, 15, 16`

위와 같은 결과를 만들어 봅시다!

```python
# 참고
for row in range(4): # 행의 갯수와
    # 빈 리스트를 만들고
    for col in range(4): #열의 갯수만큼 반복합니다.
        # 각 요소는 row와 col과 어떤 관계가 있을까요? 
```

In [31]:
len(range(4))

4

In [111]:
# write your code here!! # hard

for row in range(1, 14, 4):
    for col in range(row, row + 3):
        print(f"{col}", end = ',')
    print(f"{row + 3}")

1,2,3,4
5,6,7,8
9,10,11,12
13,14,15,16


In [23]:
# Session

for row in range(4):
    a = []
    for col in range(4):
        attribute = 4 * row + col + 1
        a.append(attribute)
    print(a)

[1, 2, 3, 4]
[5, 6, 7, 8]
[9, 10, 11, 12]
[13, 14, 15, 16]


# Q19.

사용자로부터 `1~9`정수를 입력 받습니다.
그리고 입력 받은 정수에 해당하는 구구단을 만들어봅시다.

`단, 입력값은 무조건 정수라고 가정합니다.
 단, 1~9 정수가 아니면 다시 입력을 받아야합니다.`

```python

# 실행 예시

1~9 정수를 입력하세요 : 10
1~9 정수를 입력하세요 : 20
1~9 정수를 입력하세요 : 5
5*1 = 5
5*2 = 10
~~
5*9 = 45
 

```

In [96]:
# write your code here!!
n = int(input("1~9 정수를 입력하세요 : "))

while n not in range (1, 10):
    n = int(input("1~9 정수를 입력하세요 : "))
    
if n in range (1, 10):
    for i in range(1, 10):
        print(f"{n}*{i} = {n*i}")

1~9 정수를 입력하세요 : 12
1~9 정수를 입력하세요 : 12
1~9 정수를 입력하세요 : 12
1~9 정수를 입력하세요 : 9
9*1 = 9
9*2 = 18
9*3 = 27
9*4 = 36
9*5 = 45
9*6 = 54
9*7 = 63
9*8 = 72
9*9 = 81


# Q20.

새로온 기계는 `N`개! 이라고 외치면 `N`개의 빵을 순식간에 만드는 기능이 있다고 합니다.

`단, 한번에 100개 초과는 힘들다고 합니다. 즉, 1~100 사이의 정수를 입력 받아야 합니다.`

```python

# 실행 예시

몇 개를 만들까요? -1
몇 개를 만들까요? 120
몇 개를 만들까요? 3
빵 1개
빵 2개
빵 3개
```

In [100]:
# write your code here!!
n = int(input("몇 개를 만들까요? : "))

while n not in range (1, 101):
    n = int(input("몇 개를 만들까요? : "))
    
if n in range (1, 101):
    for i in range(1, n+1):
        print(f"빵 {i}개")

몇 개를 만들까요? : 120
몇 개를 만들까요? : 110
몇 개를 만들까요? : -1
몇 개를 만들까요? : 2
빵 1개
빵 2개


In [26]:
# Session 1

try:

    num = 0 # initial

    while num < 1 or num > 100: # exit
        num = int(input("몇 개를 만들까요?"))

except ValueError:
    pass
        
for i in range(num):
    print(f"빵 {i+1}개")

몇 개를 만들까요?err


In [27]:
# Session 2

def 빵공장():
    num = 0 # initial

    while num < 1 or num > 100: # exit
        num = int(input("몇 개를 만들까요?"))

    for i in range(num):
        print(f"빵 {i+1}개")
        
    return

빵공장()

몇 개를 만들까요?121
몇 개를 만들까요?11
빵 1개
빵 2개
빵 3개
빵 4개
빵 5개
빵 6개
빵 7개
빵 8개
빵 9개
빵 10개
빵 11개


# 함수

# Q21.

다음 조건에 맞는 함수를 작성하세요.

```함수명: y
input: x (단, x는 실수 ex, 1, 1.2, 5, 100)
output:2x+1 ```

In [24]:
# write your code here!!
def y(x):
    return 2 * x + 1

In [25]:
y(1.2)

3.4

# Q22.

빵 이름과 갯수를 입력 매개변수(parameter)로 하는 함수를 만들어서 실행 해보세요. 단, 갯수을 입력하지 않으면 자동으로 주어진 종류의 빵을 3개를 만드는 함수를 만들어야합니다.

<a href ="http://studymake.blogspot.com/2015/05/default-parameter.html">참고자료</a>


`hint`
```python
# 다음과 같이 매개변수에 기본값을 지정할 수 있습니다.
def func(a="default"):
~~
```

```python

# 실행예시

exercise("초코빵", 2)
    초코빵(을)를 1개 만들었습니다.
    초코빵(을)를 2개 만들었습니다.
    작업을 끝냈습니다.
    
exercise("크림빵")
    크림빵(을)를 1개 만들었습니다.
    크림빵(을)를 2개 만들었습니다.
    크림빵(을)를 3개 만들었습니다.
    작업을 끝냈습니다.
    
```

In [103]:
# write your code here!!
def bread(x, y = 3):
    for i in range(1, y + 1):
        print(f"{x}(을)(를) {i}개 만들었습니다.")
    print("작업을 끝냈습니다.")

bread("초코빵", 2)

bread("크림빵")

초코빵(을)(를) 1개 만들었습니다.
초코빵(을)(를) 2개 만들었습니다.
작업을 끝냈습니다.
크림빵(을)(를) 1개 만들었습니다.
크림빵(을)(를) 2개 만들었습니다.
크림빵(을)(를) 3개 만들었습니다.
작업을 끝냈습니다.


# Q23.

정렬되지 않은 리스트를 매개변수로 전달했을 때, 정렬된 리스트가 반환되는 함수를 작성하세요.

```python

# 실행 예시

unordered = [5, 4, 2 ,10, 7, 3]
sorting(unordered)
    
    [2, 3, 4, 5, 7, 10]
```

In [7]:
# write your code here!!
unordered = [5, 4, 2 ,10, 7, 3]

print(sorted(unordered))

[2, 3, 4, 5, 7, 10]


# Q24.


함수에 두 개의 숫자를 전달 했을 때 사칙연산(더하기, 빼기, 곱하기, 나누기)을 수행하는 함수를 만드세요.

`(함수명, 변수명 등은 자유롭게)`

In [54]:
# write your code here!!

def Rule(a, b):
    print(a + b)
    print(a - b)
    print(a * b)
    print(a / b)

a = int(input("a = "))
b = int(input("b = "))

Rule(a, b)

a = 1
b = 2
3
-1
2
0.5


# Q25.

다음의 조건에 맞는 함수를 작성하세요.

1. 함수명: email_classification
2. input: 이메일 주소 리스트 (ex, `[abc132@naver.com, wow880@gmail.com, hahahahaha@naver.com]`)
3. ouput: key값이 메일사이트(naver, gmail), value가 id리스트인 딕셔너리


`단, 메일 사이트는 naver와 gamail 두개 밖에 존재하지 않는다고 가정한다.`

```python

#실행예시

email_claissification(['abc132@naver.com', 'wow880@gmail.com', 'hahahahaha@naver.com'])

# 결과
{'naver':['abc123', 'hahahahahaha'], 'gmail':['wow880']}
    


```

In [121]:
# practice

input = ['abc132@naver.com', 'wow880@gmail.com', 'hahahahaha@naver.com']
output = {}

#'naver.com' in input[0].split("@", 2)

for i in input:
    if 'naver.com' in i.split("@", 2):
            output['naver'] = i.split("@", 2)[0]
    if 'gmail.com' in i.split("@", 2):
            output['gmail'] = i.split("@", 2)[0]
            
output

{'naver': 'hahahahaha', 'gmail': 'wow880'}

In [125]:
# write your code here!!

def email_classification(x, y):
    naver = []
    gmail = []
    
    for i in x:
        if 'naver.com' in i.split("@", 2):
            naver.append(i.split("@", 2)[0])
        if 'gmail.com' in i.split("@", 2):
            gmail.append(i.split("@", 2)[0])
    
    y['naver'] = naver
    y['gmail'] = gmail
    
    return y

input = ['abc132@naver.com', 'wow880@gmail.com', 'hahahahaha@naver.com']
output = {}

email_classification(input, output)

{'naver': ['abc132', 'hahahahaha'], 'gmail': ['wow880']}

In [35]:
# Session

def email_classification(email_list):
    
    result = {}
    user_id_list_naver = []
    user_id_list_gmail = []
    
    for email in email_list:
        user_id = email.split('@')[0]
        mail_site = email.split('@')[1].split(".")[0]
        
        if mail_site == "gmail":
            user_id_list_gmail.append(user_id)
        else:
            user_id_list_naver.append(user_id)
    
    result['gmail'] = user_id_list_gmail
    result['naver'] = user_id_list_naver
    
    return result

email_classification(['abc132@naver.com', 'wow880@gmail.com', 'hahahahaha@naver.com'])

{'gmail': ['wow880'], 'naver': ['abc132', 'hahahahaha']}